import type { InterviewQuestion } from '../../types'

export const typographyQuestions: InterviewQuestion[] = [
  {
    id: 40,
    category: 'Typography & Visual',
    question: 'How do font-family stacks work and why use them?',
    answer: 'A font-family stack is an ordered list of typefaces where the browser uses the first font that is installed on the user\'s system or successfully loaded via @font-face. You should always end the stack with a generic family keyword like sans-serif, serif, or monospace so text still renders if every named font fails. Generic keywords map to the user\'s OS defaults, which keeps typography readable across platforms.',
    code: `body {
  font-family: "Inter", system-ui, -apple-system,
    "Segoe UI", Roboto, sans-serif;
}

code, pre {
  font-family: "JetBrains Mono", "Fira Code",
    ui-monospace, monospace;
}`,
  },
  {
    id: 41,
    category: 'Typography & Visual',
    question: 'How do you load custom web fonts with @font-face?',
    answer: '@font-face declares a custom font resource the browser can download and use like a locally installed typeface. You specify src with modern WOFF2 first for best compression, then older formats as fallbacks, and optionally define font-weight and font-style so one family name can cover multiple files. Without @font-face, the browser only uses fonts already on the device or generic families.',
    code: `@font-face {
  font-family: "Brand Sans";
  src: url("/fonts/brand-sans.woff2") format("woff2"),
       url("/fonts/brand-sans.woff") format("woff");
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

h1 {
  font-family: "Brand Sans", sans-serif;
}`,
  },
  {
    id: 42,
    category: 'Typography & Visual',
    question: 'What does the font-display property control?',
    answer: 'font-display tells the browser how to render text while a web font is still downloading, trading off between invisible text, flash of unstyled text (FOUT), and layout shift. swap shows fallback text immediately and swaps to the web font once loaded, which is the most common choice for body copy. optional gives the browser permission to skip the web font entirely on slow connections if it would delay rendering.',
    code: `@font-face {
  font-family: "Display Serif";
  src: url("/fonts/display-serif.woff2") format("woff2");
  font-display: swap; /* show fallback, swap when ready */
}

.hero-title {
  font-family: "Display Serif", Georgia, serif;
}`,
  },
  {
    id: 43,
    category: 'Typography & Visual',
    question: 'How does line-height affect typography and layout?',
    answer: 'line-height sets the vertical space each line of text occupies, controlling readability and the rhythm between lines in a block of copy. It is a unitless multiplier relative to the element\'s font-size, so line-height: 1.5 on 16px text yields 24px line boxes. Values that are too tight make descenders collide with ascenders on the next line, while values that are too loose waste space and weaken visual grouping.',
    code: `p {
  font-size: 1rem;
  line-height: 1.6; /* unitless — scales with font-size */
}

h2 {
  font-size: 2rem;
  line-height: 1.2;
  margin-bottom: 0.5em;
}`,
  },
  {
    id: 44,
    category: 'Typography & Visual',
    question: 'What is letter-spacing and when should you adjust it?',
    answer: 'letter-spacing (also called tracking) adds or removes space between individual characters without changing the font itself. Positive values improve legibility in all-caps labels and small button text where default spacing feels cramped. Negative values can tighten large display headings so they feel more cohesive, but over-tightening hurts readability in body copy.',
    code: `.nav-link {
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.display-heading {
  font-size: 3.5rem;
  letter-spacing: -0.02em;
}`,
  },
  {
    id: 45,
    category: 'Typography & Visual',
    question: 'What are the differences between hex, hsl, and oklch color formats?',
    answer: 'Hex (#rrggbb) is compact and universally supported but hard to adjust programmatically because it encodes RGB channels in hexadecimal. HSL (hue, saturation, lightness) is more intuitive for designers — you can lighten a brand color by increasing L without touching hue. OKLCH is a perceptually uniform space where equal lightness steps look equally different to the human eye, making accessible contrast tuning and gradient interpolation more predictable.',
    code: `:root {
  --brand-hex: #3b82f6;
  --brand-hsl: hsl(217 91% 60%);
  --brand-oklch: oklch(0.62 0.19 255);

  --surface: oklch(0.98 0.01 255);
  --text: oklch(0.25 0.02 255);
}

.badge {
  background: var(--brand-oklch);
  color: white;
}`,
  },
  {
    id: 46,
    category: 'Typography & Visual',
    question: 'How do CSS gradients work?',
    answer: 'CSS gradients are image values generated by the browser — they are not standalone color properties but can be used anywhere an image is accepted, such as background-image or border-image. linear-gradient creates a transition along a direction or angle, while radial-gradient radiates from a center point. You can stack multiple color stops and combine gradients with background-size for patterns like striped progress bars.',
    code: `.hero {
  background:
    linear-gradient(
      135deg,
      oklch(0.45 0.15 280 / 0.85),
      oklch(0.35 0.12 240 / 0.9)
    ),
    url("/images/hero.jpg") center / cover;
}

.progress-bar {
  background: linear-gradient(
    90deg,
    #22c55e 0%,
    #22c55e var(--pct),
    #e5e7eb var(--pct)
  );
}`,
  },
  {
    id: 47,
    category: 'Typography & Visual',
    question: 'How does box-shadow create depth and elevation?',
    answer: 'box-shadow draws one or more shadows outside (or inset inside) an element\'s border box without affecting layout or triggering reflow. Each shadow accepts horizontal offset, vertical offset, blur radius, spread radius, and color — comma-separated values stack multiple layers. Soft, large blurs with low opacity mimic ambient light and create a floating card effect, while tight shadows suggest a pressed button.',
    code: `.card {
  box-shadow:
    0 1px 2px rgb(0 0 0 / 0.06),
    0 4px 12px rgb(0 0 0 / 0.08);
}

.card:hover {
  box-shadow:
    0 2px 4px rgb(0 0 0 / 0.08),
    0 8px 24px rgb(0 0 0 / 0.12);
}

.btn:active {
  box-shadow: inset 0 2px 4px rgb(0 0 0 / 0.15);
}`,
  },
  {
    id: 48,
    category: 'Typography & Visual',
    question: 'What can you do with border-radius beyond simple rounding?',
    answer: 'border-radius controls the curvature of an element\'s corners, and each corner can be set independently using slash syntax for elliptical radii. A single value like 9999px or 50% on equal width and height creates perfect circles and pill-shaped buttons. Percentage values are relative to the element\'s own dimensions, so the same 50% radius looks different on a wide rectangle versus a square.',
    code: `.avatar {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  overflow: hidden;
}

.pill-button {
  border-radius: 9999px;
  padding: 0.5rem 1.25rem;
}

.speech-bubble {
  border-radius: 1rem 1rem 1rem 0.25rem;
}`,
  },
  {
    id: 49,
    category: 'Typography & Visual',
    question: 'What is backdrop-filter and how is it used?',
    answer: 'backdrop-filter applies visual effects like blur, brightness, or saturation to the content behind an element, creating frosted-glass or dimmed-overlay effects. Unlike filter, which affects the element itself, backdrop-filter processes whatever is rendered underneath — typically combined with a semi-transparent background color. It requires the element to be at least partially transparent, and support varies slightly across browsers for some filter functions.',
    code: `.glass-nav {
  position: sticky;
  top: 0;
  background: rgb(255 255 255 / 0.72);
  backdrop-filter: blur(12px) saturate(1.4);
  -webkit-backdrop-filter: blur(12px) saturate(1.4);
  border-bottom: 1px solid rgb(0 0 0 / 0.06);
}

.modal-overlay {
  background: rgb(0 0 0 / 0.4);
  backdrop-filter: blur(4px);
}`,
  },
]
